#pop_error.kv
<Pop_Error>:
    background_color: constants.APP_BG
    title_size: '18sp'
    title_font: constants.DIR_FONTS + "cmunobx.ttf"
    title_color: (0.8, 0, 0, 1)
    separator_color: (0.4, 0, 0, 1)
    separator_height: '3dp'
    ColBoxLayout_1:
        id: box_lbl    
        orientation: 'vertical'
        padding: 5
        spacing: 5
        ColBoxLayout_1:
            #size_hint_y: None
            Lbl_Big:
                id: content_label
                text: root.err_msg
                height: self.texture_size[1]
                halign: 'center'
                valign: 'middle'
                text_size: self.width, None
        ColBoxLayout_2:
            padding: 2
            size_hint_y: None
            height: dp(50)
            ColBoxLayout_3:
                Btn_Clear_1:
                    id: btn_close
                    on_release: root.dismiss()