<Pop_Auth_User@Popup>:
    auto_dismiss: False
    size_hint: (0.75, 0.5)
    background_color: fs22_n
    title_size: '23sp'
    title_font: constants.DIR_FONTS + "cmunobx.ttf"
    title_color: fs22_n
    separator_color: fs22_d
    separator_height: '4dp'
    BoxUnlined:
        orientation: 'vertical'
        padding: 2
        spacing: 4
        BoxLined_1:
            orientation: 'vertical'
            padding: 2
            spacing: 2
            BoxLined_1:
                Lbl_Small:
                    id: lab_inf_create_user
                    size_hint: (1, None)
                    height: 200
                    text_size: (self.width - 40, None)
                    halign: 'center'
                    valign: 'middle'
                    font_size: "25dp"
            BoxLined_1:
                size_hint_y: None 
                height: "40dp"
                TextInput:
                    id: inp_username
                    multiline: False
                    font_size: "23dp"
            BoxLined_1:
                size_hint_y: None
                height: "42dp"
                BoxLayout:
                    TextInput:
                        id: inp_passwd
                        password: True  # Initial versteckt
                        multiline: False
                        font_size: "23dp"
                        on_text_validate: root.but_confirm_released()  
                    ToggleButton:
                        size_hint_x: None
                        width: "34dp"
                        text: " " if self.state == "normal" else "X"
                        on_release: inp_passwd.password = not self.state == "down"
            BoxLined_2:
                orientation: "vertical"
                padding: 4
                spacing: 8
                BoxLined_2:
                    height: "40dp"
                    Btn_Clear:
                        id: but_confirm
                        on_release: root.but_confirm_released()
                BoxLined_2:
                    height: "40dp"
                    Btn_Clear:
                        id: but_chancel
                        on_release: root._close_popup()
                    
            