#: import constants constants

<Pop_Auth_User@Popup>:
    auto_dismiss: False
    size_hint: (0.75, 0.5)
    background_color: constants.APP_BG
    title_size: '23sp'
    title_font: constants.DIR_FONTS + "cmunobx.ttf"
    title_color: constants.POP_TITLE
    separator_color: constants.POP_SEPARATOR
    separator_height: '4dp'
    ColBoxLayout_1:
        orientation: 'vertical'
        padding: 2
        spacing: 4
        ColBoxLayout_4:
            orientation: 'vertical'
            padding: 2
            spacing: 2
            ColBoxLayout_2:
                Lbl_Small:
                    id: lab_inf_create_user
                    size_hint: (1, None)
                    height: 200
                    text_size: (self.width - 40, None)
                    halign: 'center'
                    valign: 'middle'
                    font_size: "25dp"
            ColBoxLayout_2:
                size_hint_y: None 
                height: "40dp"
                TextInput:
                    id: inp_username
                    multiline: False
                    font_size: "23dp"
            ColBoxLayout_2:
                size_hint_y: None
                height: "42dp"
                ColBoxLayout_2:
                    TextInput:
                        id: inp_passwd
                        password: True  # Initial versteckt
                        multiline: False
                        font_size: "23dp"
                        on_text_validate: root.but_confirm_released()  
                    ToggleButton:
                        size_hint_x: None
                        width: "34dp"
                        text: " " if self.state == "normal" else "X"
                        on_release: inp_passwd.password = not self.state == "down"
            ColBoxLayout_1:
                orientation: "vertical"
                padding: 2
                ColBoxLayout_4:
                    padding: 2
                    spacing: 8
                    ColBoxLayout_2:
                        height: "40dp"
                        Btn_Clear:
                            id: but_confirm
                            on_release: root.but_confirm_released()
                    ColBoxLayout_2:
                        height: "40dp"
                        Btn_Clear:
                            id: but_chancel
                            on_release: root._close_popup()
                    
            