<Page_Load_Scr>:
    FloatLayout:
        Image:
            source: root.spl_scr  # Pass the splash screen image path via the constructor
            allow_stretch: True
            keep_ratio: False
            size_hint: 1, 1

        ProgressBar:
            id: progress_bar
            max: 100
            value: 0
            size_hint: 0.75, 0.05
            pos_hint: {"center_x": 0.5, "y": 0.16}

        Label:
            id: status_label
            text: root.txt_lab["loading"]
            font_size: "42sp"
            size_hint: 0.8, 0.1
            pos_hint: {"x": 0.1, "y": 0.12}
            halign: "center"
            valign: "middle"