#settingpage.kv
#: import constants constants
<SettingPage>:
    BoxLayout:
        orientation: 'vertical'
# Titelbox aus dem fil own_widgets.kv
        BoxTitle:
            id: t_box_sett
        BoxLined_2:
            id: m_box_settings
            orientation: 'vertical'
            spacing: 2
            padding: 2
            BoxUnlined:
                size_hint_y: 0.1
# Label für Titel Sprachauswahl                
                Lbl_Big:
                    id: lab_tit_lang
            BoxUnlined:
                orientation: 'vertical'
                size_hint_y: 0.2
                padding: 4, 0, 4, 0
                spacing: 2
# Box für die erste Sprache
                BoxFlag:
                    id: box_flag_1
# Box für die zweite Sprache
                BoxFlag:
                    id: box_flag_2
            BoxUnlined:
                size_hint_y: None
                height: "20dp"
                BoxLined_1:
                    Lbl_Small:
                        id: lbl_add_new_user
                    Btn_Clear:
                        id: btn_add_new_user
            BoxUnlined:
# Box Fusszeile    
            BoxBottom:
                id: b_box_settings
