# own_widgets.kv
#: import constants constants
###
# vordefinierte BoxLayouts
###
# Definiere BoxUnlined mit einer Hintergrundfarbe
<BoxUnlined@BoxLayout>:
    canvas.before:
        Color:
            rgba: app.color1
        Rectangle:
            size: self.size
            pos: self.pos
    id: box_col_1
    
# Definiere BoxLined_1 mit einer Rahmenfarbe
<BoxLined_1@BoxLayout>:
    canvas.before:
        Color:
            rgba: app.color2
        Line:
            width: 1  # Breite des Randes
            rectangle: self.x, self.y, self.width, self.height  # Rechteck für den Rand
    id: box_line_1
    background_color: app.color1

# Definiere BoxLined_1 mit einer Rahmenfarbe
<BoxLined_2@BoxLayout>:
    canvas.before:
        Color:
            rgba: app.color3
        Line:
            width: 1  # Breite des Randes
            rectangle: self.x, self.y, self.width, self.height  # Rechteck für den Rand
    id: box_line_2
###
# vordefinierte Buttons und sonstiges die in die app eingefügt werden können.
###

<Logo_Main@Image>:
    source: constants.PATH_TO_MAINLOGO


###
# vordefinierte Widgets die in die app eingefügt werden können.
###
# Languagebox
<BoxFlag@BoxUnlined>:
    orientation: 'vertical'
    spacing: 4
    BoxLined_2:
        padding: 2
        BoxUnlined:
            size_hint_x: 0.25
            Image:
                id: img_flag
        BoxUnlined:
            Btn_Clear:
                id: lab_but_flag
                #on_release: app.change_language(self.text.lower())

# Titelbox
<BoxTitle@BoxLayout>:
    size_hint_y: None
    height: "32dp"
    BoxUnlined:
        padding: 2
        BoxLined_1:
            BoxUnlined:
                size_hint_x: 0.2            
                Logo_Main:
            BoxUnlined:
                # Label für Seitentitel
                Lbl_Big:
                    id: lab_tit_page
                    font_size: self.height * 0.8
                    halign: 'center'
                    color: grey2
            BoxUnlined:
                size_hint_x: 0.2
                Btn_Clear:
                    id: but_info
                    text: "?"
                    halign: 'right'
                    on_release: app.open_inf_pop()
###
# Bottombox
<BoxBottom@BoxLayout>:
    size_hint_y: None
    height: "32dp"
    BoxUnlined:
        padding: 2
        BoxLined_1:
            Btn_Clear:
                id: but_1
                font_size: self.height * 0.5
                on_release: app.change_screen('left', 'page_setting') if app.scr_man.current == 'page_start' else app.change_screen('right', 'page_start')
            
            # Box Button right in Bottombox            
            Btn_Clear:
                id: but_2
                font_size: self.height * 0.5
                on_release: app.stop()

<BoxRed@BoxLayout>:
    canvas.before:
        Color:
            rgb: 1,0,0
        Rectangle:
            size: self.size
            pos: self.pos