# own_widgets.kv
#: import constants constants

<Logo_Main@Image>:
    source: constants.PATH_TO_MAINLOGO_D


# Languagebox
<BoxFlag@ColBoxLayout_1>:
    padding: 1
    spacing: 4
    size_hint_y: None
    height: "36dp"
    ColBoxLayout_4:
        padding: 1
        ColBoxLayout_1:
            padding: 1
            # imagebox
            ColBoxLayout_2:
                size_hint_x: 0.25
                padding: 0, 2, 0, 2
                Image:
                    id: img_flag
            # buttonbox
            ColBoxLayout_2:
                padding: 2
                ColBoxLayout_1:
                    padding: 2
                    ColBoxLayout_3:
                        Btn_Clear:
                            id: but_flag
                            font_size: "21dp"

# Titelbox
<BoxTitle@ColBoxLayout_2>:
    size_hint_y: None
    height: "40dp"
    ColBoxLayout_1:
        size_hint_x: 0.2
        padding: 0, 3, 0, 3           
        Logo_Main:
            id: img_logo_main
    ColBoxLayout_1:
        Lbl_Big:
            id: lab_tit_page
    ColBoxLayout_1:
        size_hint_x: 0.2
        Btn_Clear:
            id: but_info
            text: "?"
            halign: 'right'
###
# Bottombox
<BoxBottom@ColBoxLayout_2>:
    size_hint_y: None
    height: "40dp"
    spacing: 4
    ColBoxLayout_1:
        padding: 4, 2, 4, 2
        ColBoxLayout_2:
            padding: 2
            # Box Button left in Bottombox            
            ColBoxLayout_1:
                padding: 4, 2, 4, 2
                Btn_Clear:
                    id: but_1
                    on_release: app.change_screen('left', 'page_setting') if app.scr_man.current == 'page_start' else app.change_screen('right', 'page_start')
        ColBoxLayout_2:
            padding: 2
            ColBoxLayout_1:
                padding: 4, 2, 4, 2
                # Box Button right in Bottombox            
                Btn_Clear:
                    id: but_2
                    on_release: app.stop()

<BoxRed@BoxLayout>:
    canvas.before:
        Color:
            rgb: 1,0,0
        Rectangle:
            size: self.size
            pos: self.pos