<Lbl_Big>:
    font_size: "23dp"
    font_name: constants.DIR_FONTS + 'Jura-DemiBold.otf'

<Lbl_Small>:
    font_size: "21dp"
    font_name: constants.DIR_FONTS + 'Jura-Light.otf'

<Btn_Clear_1>:
    background_color: 0,0,0,0
    font_name: constants.DIR_FONTS + 'Jura-Medium.otf'
    font_size: "18dp"

<Btn_Clear_2>:
    background_color: 0,0,0,0
    font_name: constants.DIR_FONTS + 'Jura-Medium.otf'
    font_size: "18dp"
